name: PROXY Updater

on:
  push:
    paths-ignore:
      - '**.txt'
      - '**.yaml'
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Update file
      env:
        LINK: ${{ secrets.LINK }}
        PYTHONUNBUFFERED: 1
      run: |
        curl https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt -o socks5.txt
        curl https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt -o socks4.txt
        curl https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt -o http.txt
        curl https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/README.md -o README.md
        python check.py
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.GIT_EMAIL }}
        git config --local user.name ${{ secrets.GIT_NAME }}
        git add -A
        git commit -am "Updated Proxies"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
